package com.tsi.melvin.program;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.springframework.boot.system.SystemProperties;

// Generated by Selenium IDE
import org.junit.Before;
import org.junit.After;

import org.junit.jupiter.api.Assertions;
import org.openqa.selenium.By;

import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;


import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class seleniumTest {


    private final String homePageUrl= "http://localhost:3000/";
    private WebDriver driver;




    @BeforeEach
    public void chromeSessionTest(){


        System.setProperty("webdriver.chrome.driver", "C:\\Users\\Melvin Joy\\IdeaProjects\\program\\chromedriver.exe");
        // this set the new driver.
        driver = new ChromeDriver();



    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void testFilmDisplay() {
        //Get this url
        driver.get("http://localhost:3000/");


        String  before = driver.findElement(By.id("showLP")).getText();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(300));
        wait.until(ExpectedConditions.invisibilityOfElementWithText(By.id("showLP"), before));
        String after = driver.findElement(By.id("showLP")).getText();

        Assertions.assertNotEquals(before, after);



    }

    @Test
    public void testAddActor() {
        //Get this url
        driver.get("http://localhost:3000/AddActor");

        WebElement first_name = driver.findElement(By.id("first_name"));
        WebElement last_name = driver.findElement(By.id("last_name"));

        first_name.sendKeys("testfirst");
        last_name.sendKeys("testlast");

        String  before = driver.findElement(By.id("success")).getText();
        WebElement addActor = driver.findElement(By.id("button"));
        addActor.click();
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(300));
        wait.until(ExpectedConditions.invisibilityOfElementWithText(By.id("success"), before));
        String after = driver.findElement(By.id("success")).getText();

        Assertions.assertNotEquals(before, after);

    }




}
